### ISSUE TITLE
Compilation from source: LESS file is empty

### ISSUE THREAD

**Issue by avstaylime** [magmodules/magento2-messagebird#4]
Hi,

Installed the extension on a migrated 2.4.7-P1 host. The logs are full of errors related to adminhtml/Magento/backend/en_US/Magmodules_MessageBird/css/styles.less:

```
[2024-07-04T10:41:33.790203+00:00] main.CRITICAL: Magento\Framework\View\Asset\ContentProcessorException: Compilation from source: LESS file is empty: adminhtml/Magento/backend/en_US/Magmodules_MessageBird/css/styles.less in /data/web/magento2/vendor/magento/framework/Css/PreProcessor/Adapter/Less/Processor.php:99
Stack trace:
#0 /data/web/magento2/vendor/magento/framework/View/Asset/PreProcessor/AlternativeSource.php(154): Magento\Framework\Css\PreProcessor\Adapter\Less\Processor->processContent()
#1 /data/web/magento2/vendor/magento/framework/View/Asset/PreProcessor/AlternativeSource.php(112): Magento\Framework\View\Asset\PreProcessor\AlternativeSource->processContent()
#2 /data/web/magento2/vendor/magento/module-developer/Model/View/Asset/PreProcessor/PreprocessorStrategy.php(78): Magento\Framework\View\Asset\PreProcessor\AlternativeSource->process()
#3 /data/web/magento2/vendor/magento/framework/View/Asset/PreProcessor/Pool.php(77): Magento\Developer\Model\View\Asset\PreProcessor\PreprocessorStrategy->process()
#4 /data/web/magento2/vendor/magento/framework/View/Asset/Source.php(155): Magento\Framework\View\Asset\PreProcessor\Pool->process()
#5 /data/web/magento2/vendor/magento/framework/View/Asset/Source.php(124): Magento\Framework\View\Asset\Source->preProcess()
#6 /data/web/magento2/vendor/magento/framework/View/Asset/File.php(186): Magento\Framework\View\Asset\Source->getContent()
#7 /data/web/magento2/vendor/magento/framework/View/Asset/MergeStrategy/Direct.php(83): Magento\Framework\View\Asset\File->getContent()
#8 /data/web/magento2/vendor/magento/framework/View/Asset/MergeStrategy/Direct.php(63): Magento\Framework\View\Asset\MergeStrategy\Direct->composeMergedContent()
#9 /data/web/magento2/vendor/magento/framework/View/Asset/MergeStrategy/FileExists.php(44): Magento\Framework\View\Asset\MergeStrategy\Direct->merge()
#10 /data/web/magento2/vendor/magento/framework/View/Asset/Merged.php(111): Magento\Framework\View\Asset\MergeStrategy\FileExists->merge()
#11 /data/web/magento2/vendor/magento/framework/View/Asset/Merged.php(183): Magento\Framework\View\Asset\Merged->initialize()
#12 /data/web/magento2/vendor/magento/framework/View/Page/Config/Renderer.php(420): Magento\Framework\View\Asset\Merged->rewind()
#13 /data/web/magento2/vendor/magento/framework/View/Page/Config/Renderer.php(297): Magento\Framework\View\Page\Config\Renderer->renderAssetHtml()
#14 /data/web/magento2/vendor/magento/framework/View/Page/Config/Renderer.php(284): Magento\Framework\View\Page\Config\Renderer->renderAssetGroup()
#15 /data/web/magento2/generated/code/Magento/Framework/View/Page/Config/Renderer/Interceptor.php(23): Magento\Framework\View\Page\Config\Renderer->renderAssets()
#16 /data/web/magento2/vendor/magento/framework/View/Page/Config/Renderer.php(137): Magento\Framework\View\Page\Config\Renderer\Interceptor->renderAssets()
#17 /data/web/magento2/vendor/magento/framework/View/Result/Page.php(252): Magento\Framework\View\Page\Config\Renderer->renderHeadContent()
#18 /data/web/magento2/vendor/magento/framework/View/Result/Layout.php(171): Magento\Framework\View\Result\Page->render()
#19 /data/web/magento2/generated/code/Magento/Backend/Model/View/Result/Page/Interceptor.php(32): Magento\Framework\View\Result\Layout->renderResult()
#20 /data/web/magento2/vendor/magento/framework/App/Http.php(120): Magento\Backend\Model\View\Result\Page\Interceptor->renderResult()
#21 /data/web/magento2/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\App\Http->launch()
#22 /data/web/magento2/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\App\Http\Interceptor->___callParent()
#23 /data/web/magento2/vendor/magento/module-application-performance-monitor/Plugin/ApplicationPerformanceMonitor.php(38): Magento\Framework\App\Http\Interceptor->Magento\Framework\Interception\{closure}()
#24 /data/web/magento2/vendor/magento/framework/Interception/Interceptor.php(135): Magento\ApplicationPerformanceMonitor\Plugin\ApplicationPerformanceMonitor->aroundLaunch()
#25 /data/web/magento2/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\App\Http\Interceptor->Magento\Framework\Interception\{closure}()
#26 /data/web/magento2/generated/code/Magento/Framework/App/Http/Interceptor.php(23): Magento\Framework\App\Http\Interceptor->___callPlugins()
#27 /data/web/magento2/vendor/magento/framework/App/Bootstrap.php(264): Magento\Framework\App\Http\Interceptor->launch()
#28 /data/web/magento2/pub/index.php(30): Magento\Framework\App\Bootstrap->run()
#29 {main} {"exception":"[object] (Magento\\Framework\\View\\Asset\\ContentProcessorException(code: 0): Compilation from source: LESS file is empty: adminhtml/Magento/backend/en_US/Magmodules_MessageBird/css/styles.less at /data/web/magento2/vendor/magento/framework/Css/PreProcessor/Adapter/Less/Processor.php:99)"} []
```

**Comment by Frank-Magmodules** [comment]
Hi @avstaylime,

As confirmed via email, we are pleased to inform you that we have just launched version [1.1.1](https://github.com/magmodules/magento2-messagebird/releases/tag/1.1.1), which addresses this issue. We are now closing this issue. If you have any further questions or encounter any problems, please feel free to ask or reopen the issue.

Thank you again for bringing this to our attention, much appreciated!
